server:
  port: 8082

spring:
  application:
    name: fraud-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: fraud-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
    properties:
      spring.json.type.mapping: "OrderEvent:com.hackathon.fraudservice.event.OrderEvent,FraudEvent:com.hackathon.fraudservice.event.FraudEvent"
